vis + gate algo refactor
berkeleyauv/perception-experiments pull request #34
Opened 2021-01-04 08:17 UTC by Axquaris

2021-01-04 20:08 UTC, AVSurfer123 requested changes

2021-01-04 20:08 UTC, AVSurfer123 commented on perception/tasks/gate/GateCenterAlgo.py
> +sys.path.append(os.path.dirname(__file__))
Remove this. Shouldn't be needed with using absolute imports

2021-01-04 20:08 UTC, AVSurfer123 commented on perception/tasks/gate/GatePerceiver.py
>  sys.path.insert(0, '..')
Again, remove this as shouldn't be needed with absolute imports

2021-01-04 20:08 UTC, AVSurfer123 commented on perception/tasks/gate/GateSegmentationAlgoA.py
> +sys.path.append(os.path.dirname(__file__))
Same thing. We should remove all path modifying lines now.

2021-01-04 20:08 UTC, AVSurfer123 commented on perception/tasks/gate/GateSegmentationAlgoB.py
> +sys.path.append(os.path.dirname(__file__))
Same thing

2021-01-04 20:08 UTC, AVSurfer123 commented on perception/tasks/gate/GateSegmentationAlgoC.py
>  sys.path.append(str(Path(__file__).parents[2]) + '/tasks')
same thing

2021-01-04 20:08 UTC, AVSurfer123 commented on requirements.txt
> -opencv-python==3.4.3.18
keep this and matplotlib only i think

2021-01-04 20:09 UTC, AVSurfer123 commented
Also why are there 3 different algorithms, A, B, C? is it just older versions? Probably should be renamed better

2021-01-05 21:13 UTC, nLevin13 requested changes
I noticed that this branch is several commits behind master, so there's a features I added to vis.py that aren't in your version, namely the pyplot integration. Can you merge from master first then apply your changes? Other than that, it seems good

2021-01-05 21:13 UTC, nLevin13 commented on perception/vis/vis.py
> +        if frame_count % speed == 0 and not paused:
If the program is paused, the loop will still run and a lot of frames will be skipped

2021-01-10 11:55 UTC, nLevin13 approved these changes

2021-01-12 08:31 UTC, AVSurfer123 approved these changes
Just 2 more small deletions and its good to go

2021-01-12 08:31 UTC, AVSurfer123 commented on perception/tasks/cross/cross_detection.py
>  sys.path.insert(0, '../background_removal')
delete this line

2021-01-12 08:31 UTC, AVSurfer123 commented on perception/tasks/gate/GateSegmentationAlgoB.py
> +sys.path.append(os.path.dirname(__file__))
I don't see this line deleted. Is this needed for some reason still?

2021-01-12 23:20 UTC, nLevin13 commented
We can remove (archive) detectGate, threshTest, and threshslider

2021-01-18 00:15 UTC, merged